# NumPy: _Numerical Python_

## Preface: Why Python?

### The scientist needs
- Get data (simulation, experiment control)
- Manipulate and process data
- Visualize results, quickly to understand, but also with high quality figures, for reports or publications

### Python’s strengths

- Batteries included
- Easy to learn
- Easy communication
- Efficient code

Python numerical modules are computationally efficient. But needless to say that a very fast code becomes useless if too much time is spent writing it. Python aims for quick development times and quick execution times.

- Universal

### How does Python compare to other solutions?

#### Compiled languages: C, C++, Fortran…

|Pros:| Cons:|
|---|---|
| Very fast. For heavy computations, it’s difficult to outperform these languages.| Painful usage: no interactivity during development, mandatory compilation steps, verbose syntax, manual memory management. These are difficult languages for non programmers.|

#### Matlab scripting language

|Pros:| Cons:|
|---|---|
|Very rich collection of libraries with numerous algorithms, for many different domains. Fast execution because these libraries are often written in a compiled language.| Base language is quite poor and can become restrictive for advanced users. |
| Pleasant development environment: comprehensive and help, integrated editor, etc. | Not free. |
| Commercial support is available.|   |

#### Julia

|Pros:| Cons:|
|---|---|
|Fast code, yet interactive and simple. | Ecosystem limited to numerical computing.|
|Easily connects to Python or C. |Still young. |

#### Other scripting languages: Scilab, Octave, R, IDL, etc.

|Pros:| Cons:|
|---|---|
|Open-source, free, or at least cheaper than Matlab. |Fewer available algorithms than in Matlab, and the language is not more advanced. |
|Some features can be very advanced (statistics in R, etc.) |Some software are dedicated to one domain. Ex: Gnuplot to draw curves. These programs are very powerful, but they are restricted to a single type of usage, such as plotting. |

#### Python

|Pros:| Cons:|
|---|---|
| Very rich scientific computing libraries| Not all the algorithms that can be found in more specialized software or toolboxes.|
| Well thought out language, allowing to write very readable and well structured code: we “code what we think”.| Ease of use comes with an efficiency compromise|
| Many libraries beyond scientific computing (web server, serial port access, etc.)| Open source often regarded as "unreliable" in corporative ecosystem|
| Free and open-source software, widely spread, with a vibrant community.| |
| A variety of powerful environments to work in, such as IPython, Spyder, Jupyter notebooks, Pycharm| |

### The Scientific Python ecosystem

- *Python*: general purpose programming language
    - Scripting language
    - Can have functional, imperative, and Object-Oriented paradigms in it
- Core numerical libraries
    - NumPy
    - SciPy
    - Matplotlib

## Refresher

### Python common data structures

- List

In [1]:
ex_list = [1, 2.0, "DSP"]
ex_list

[1, 2.0, 'DSP']

List creation

In [8]:
ex_list = list(range(1, 10))
ex_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

- Slicing

Structure:

```python
a_list[start:stop:step]
```

In [9]:
ex_list[2:]

[3, 4, 5, 6, 7, 8, 9]

In [10]:
ex_list[:5]

[1, 2, 3, 4, 5]

In [12]:
ex_list[::-2]

[9, 7, 5, 3, 1]

- Reference

In [13]:
ex2_list = ex_list
ex2_list[0] = -1
print("ex: ", ex_list)
print("ex2: ", ex2_list)

ex:  [-1, 2, 3, 4, 5, 6, 7, 8, 9]
ex2:  [-1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
ex3_list = ex_list[:]
ex3_list[0] = 0
print("ex: ", ex_list)
print("ex3: ", ex3_list)

ex:  [-1, 2, 3, 4, 5, 6, 7, 8, 9]
ex3:  [0, 2, 3, 4, 5, 6, 7, 8, 9]


- Function definition

In [15]:
def transpose(mat_in, mat_out):
    rows = len(mat_in)
    cols = len(mat_in[0])
    for j in range(rows):
        mat_out.append([])
        for i in range(cols):
            mat_out[j].append(mat_in[i][j])

In [16]:
ex_dlist = []
dim = 10
for i in range(dim):
    ex_dlist.append(list(range(dim)))
    
ex2_dlist = []

transpose(ex_dlist, ex2_dlist)

print("ex: ", ex_dlist)
print("\n\n")
print("ex2: ", ex2_dlist)

ex:  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]



ex2:  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [4, 4, 4, 4, 4, 4, 4, 4, 4, 4], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5], [6, 6, 6, 6, 6, 6, 6, 6, 6, 6], [7, 7, 7, 7, 7, 7, 7, 7, 7, 7], [8, 8, 8, 8, 8, 8, 8, 8, 8, 8], [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]]


- Dictionaries

In [19]:
ex_dict = {
    "DSP10" : "The best one",
    "DSP11" : "We will see..."
}

ex_dict[0]

KeyError: 0

- **Object Orientation:** Clases and objects

In [20]:
class DSP:
    def __init__(self, Modules, Trainers, Version=11):
        self.Module = Modules
        self.Trainers = Trainers
        self.Version = Version
    def echoVersion(self):
        print("DSP version ", self.Version)

In [27]:
xi = DSP(Modules=3, Trainers=["Cristian", "Panshow", "Gerson"])
x = DSP(Modules=2, Trainers=["Panshow"], Version=10)
xi.echoVersion()
xi.Trainers[0] = "Felipe"
print(x.Trainers[0], x.Module)
print(xi.Trainers[0], xi.Module)
x.echoVersion(xi)

DSP version  11
Panshow 2
Felipe 3


TypeError: echoVersion() takes 1 positional argument but 2 were given

- Inheritance

In [28]:
class Polygon:
    def __init__(self, no_of_sides):
        self.n = no_of_sides
        self.sides = [0 for i in range(no_of_sides)]

    def inputSides(self):
        self.sides = [float(input("Enter side "+str(i+1)+" : ")) for i in range(self.n)]

    def dispSides(self):
        for i in range(self.n):
            print("Side",i+1,"is",self.sides[i])

class Triangle(Polygon):
    def __init__(self):
        Polygon.__init__(self, 3)

    def findArea(self):
        a, b, c = self.sides
        # calculate the semi-perimeter
        s = (a + b + c) / 2
        area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
        print('The area of the triangle is %0.2f' %area)

In [29]:
ex_triangle = Triangle()
ex_triangle.inputSides()

Enter side 1 : 3
Enter side 2 : 4
Enter side 3 : 5


In [30]:
ex_triangle.findArea()

The area of the triangle is 6.00


## NumPy, at last

In [1]:
import numpy as np

In [8]:
a = np.array([2, 4., 6.])

In [9]:
a

array([2., 4., 6.])

In [15]:
np.ones((3, 3, 2), dtype=np.int16)

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [19]:
np.zeros((3, 2), dtype=np.int16)

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [24]:
x = np.arange(0, 10, .1)
y = np.sin(x)
y

array([ 0.        ,  0.09983342,  0.19866933,  0.29552021,  0.38941834,
        0.47942554,  0.56464247,  0.64421769,  0.71735609,  0.78332691,
        0.84147098,  0.89120736,  0.93203909,  0.96355819,  0.98544973,
        0.99749499,  0.9995736 ,  0.99166481,  0.97384763,  0.94630009,
        0.90929743,  0.86320937,  0.8084964 ,  0.74570521,  0.67546318,
        0.59847214,  0.51550137,  0.42737988,  0.33498815,  0.23924933,
        0.14112001,  0.04158066, -0.05837414, -0.15774569, -0.2555411 ,
       -0.35078323, -0.44252044, -0.52983614, -0.61185789, -0.68776616,
       -0.7568025 , -0.81827711, -0.87157577, -0.91616594, -0.95160207,
       -0.97753012, -0.993691  , -0.99992326, -0.99616461, -0.98245261,
       -0.95892427, -0.92581468, -0.88345466, -0.83226744, -0.77276449,
       -0.70554033, -0.63126664, -0.55068554, -0.46460218, -0.37387666,
       -0.2794155 , -0.1821625 , -0.0830894 ,  0.0168139 ,  0.1165492 ,
        0.21511999,  0.31154136,  0.40484992,  0.49411335,  0.57

In [27]:
np.tile(-3.14, (5, 3))

array([[-3.14, -3.14, -3.14],
       [-3.14, -3.14, -3.14],
       [-3.14, -3.14, -3.14],
       [-3.14, -3.14, -3.14],
       [-3.14, -3.14, -3.14]])

In [28]:
np.repeat([1, 2], 5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [29]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [30]:
np.matrix('1, 2; 3, 4')

matrix([[1, 2],
        [3, 4]])

In [31]:
x = np.array([('a', 0.8), ('b', 0.2)], dtype=[('label', 'a8'), ('prob', 'f8')])

In [32]:
x['label']

array([b'a', b'b'], dtype='|S8')

In [28]:
x['prob']

array([0.8, 0.2])

In [33]:
a = np.array([2, 4, 6])
b = np.array([8, 10, 12])

In [34]:
a + b

array([10, 14, 18])

In [35]:
a + 1

array([3, 5, 7])

In [36]:
a - 9

array([-7, -5, -3])

In [37]:
a * 10

array([20, 40, 60])

Broadcasting vectorizes the operation so that it's as if the scalars 1, 9 and 10 we're repeated to form an array with the same dimensions as a to allow the operation.

- **Some rules for Numpy broadcasting**

Taken from the Numpy documentation - <br>
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

* they are equal, or
* one of them is 1

In [40]:
a = np.arange(100).reshape(20, 5)
b = np.arange(40).reshape(20, 2)

In [41]:
a + b

ValueError: operands could not be broadcast together with shapes (20,5) (20,2) 

#### Broadcasting: exercises

In [42]:
a = np.ones((9, 8, 1, 3, 3))
b = np.ones((1, 8, 9, 1, 3))

Can they be broadcasted?

In [43]:
a + b

array([[[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         ...,

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]],


        [[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         ...,

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]],


        [[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

    

And this one?

In [38]:
a = np.ones((9, 1, 2))
b = np.ones((1, 9, 8))
a + b

ValueError: operands could not be broadcast together with shapes (9,1,2) (1,9,8) 

### Indexing

In [45]:
a = np.arange(25)
print(a.shape)

(25,)


In [49]:
a[:, np.newaxis]
a.shape

(25,)

In [59]:
a = np.arange(9).reshape(3, 3, 1)

In [60]:
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [62]:
a[1, ...]

array([[3],
       [4],
       [5]])

In [63]:
a[1, :, :]

array([[3],
       [4],
       [5]])

In [64]:
a = a.squeeze()

In [65]:
a.shape

(3, 3)

In [47]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
a[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24]]])

In [49]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
a[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

array([ 0,  6, 12, 18, 24])

In [51]:
x = a[0:2].copy()
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [52]:
x[0, 0] = 100
print(x)

[[100   1   2   3   4]
 [  5   6   7   8   9]]


In [53]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

What will the output of this be?

In [54]:
a[::2, [1, 3, 4]]

array([[ 1,  3,  4],
       [11, 13, 14],
       [21, 23, 24]])

#### Indexing: Exercises

In [55]:
a = np.arange(25).reshape((5, 5))
b = np.arange(75).reshape((5, 5, 3))
print("a:\n", a)
print("\n\n")
print("b:\n", b)

a:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]



b:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]

 [[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]]


How can we sum both?

- reshape
- np.newaxis

* Add the two arrays together (remember the rules for broadcasting)
* Acess the first and last element of every alternate row

NumPy arrays are passed by reference

In [56]:
a = np.array([1, 2, 3, 4, 5])

In [57]:
b = a

In [58]:
b is a

True

In [59]:
np.may_share_memory(a, b)

True

In [60]:
a[1] = 100
print("a:\n", a)
print("\n\n")
print("b:\n", b)

a:
 [  1 100   3   4   5]



b:
 [  1 100   3   4   5]


## Exercise

Using documentation functions (np?, np.lookfor(), help(np.whatever_function)), create a 2nd degree list of points, add normally distributed noise, and then perform a polynomial regression using least squares, and then compare the obtained coefficients with the ones you started

In [61]:
## Answer

In [62]:
np?

In [64]:
np.lookfor("poly")

Search results for 'poly'
-------------------------
numpy.poly
    Find the coefficients of a polynomial with the given sequence of roots.
numpy.poly1d
    A one-dimensional polynomial class.
numpy.polyadd
    Find the sum of two polynomials.
numpy.polyder
    Return the derivative of the specified order of a polynomial.
numpy.polydiv
    Returns the quotient and remainder of polynomial division.
numpy.polyfit
    Least squares polynomial fit.
numpy.polyint
    Return an antiderivative (indefinite integral) of a polynomial.
numpy.polymul
    Find the product of two polynomials.
numpy.polysub
    Difference (subtraction) of two polynomials.
numpy.polyval
    Evaluate a polynomial at specific values.
numpy.roots
    Return the roots of a polynomial with coefficients given in p.
numpy.ma.polyfit
    Least squares polynomial fit.
numpy.RankWarning
    Issued by `polyfit` when the Vandermonde matrix is rank deficient.
numpy.poly1d.deriv
    Return a derivative of this polynomial.
numpy.poly

In [65]:
help(np.polyfit)

Help on function polyfit in module numpy:

polyfit(x, y, deg, rcond=None, full=False, w=None, cov=False)
    Least squares polynomial fit.
    
    Fit a polynomial ``p(x) = p[0] * x**deg + ... + p[deg]`` of degree `deg`
    to points `(x, y)`. Returns a vector of coefficients `p` that minimises
    the squared error in the order `deg`, `deg-1`, ... `0`.
    
    The `Polynomial.fit <numpy.polynomial.polynomial.Polynomial.fit>` class
    method is recommended for new code as it is more stable numerically. See
    the documentation of the method for more information.
    
    Parameters
    ----------
    x : array_like, shape (M,)
        x-coordinates of the M sample points ``(x[i], y[i])``.
    y : array_like, shape (M,) or (M, K)
        y-coordinates of the sample points. Several data sets of sample
        points sharing the same x-coordinates can be fitted at once by
        passing in a 2D-array that contains one dataset per column.
    deg : int
        Degree of the fitting po

In [66]:
x = np.linspace(start=-1.0, stop=1.0, num=20)
sigma = 0.25
mu = 0.0
noise = mu + sigma*np.random.randn(len(x))

In [67]:
x = x + noise
y = x**2 + 2
z = np.polyfit(x, y, 2)

In [68]:
z

array([1.00000000e+00, 1.92300829e-15, 2.00000000e+00])